// Autogenerated OSC data file: osc_tree.h
//
// This file was generated by the gen_osc.pl script from the following files:
//    ./src/audio_monitor.osc
//    ./../../ap_avb/module_avb/src/avb.osc
//    ./../../ap_avb/module_avb/src/avb_ptp.osc
//    ./../../ap_avb/module_osc/src/base.osc
//
// See the module_osc README file for more details
//
#ifndef _osc_tree_h_
#define _osc_tree_h_
enum osc_node_type {
  OSC_NODE_OSC,
  OSC_NODE_OSC_VERSION,
  OSC_NODE_OSC_TYPE,
  OSC_NODE_OSC_TYPE_REPORTS,
  OSC_NODE_OSC_TYPE_ACCEPTS,
  OSC_NODE_AVB,
  OSC_NODE_AVB_SOURCE,
  OSC_NODE_AVB_SOURCE_HASH,
  OSC_NODE_AVB_SOURCE_HASH_PRESENTATION,
  OSC_NODE_AVB_SOURCE_HASH_MAP,
  OSC_NODE_AVB_SOURCE_HASH_DEST,
  OSC_NODE_AVB_SOURCE_HASH_FORMAT,
  OSC_NODE_AVB_SOURCE_HASH_CHANNELS,
  OSC_NODE_AVB_SOURCE_HASH_SYNC,
  OSC_NODE_AVB_SOURCE_HASH_NAME,
  OSC_NODE_AVB_SOURCE_HASH_ID,
  OSC_NODE_AVB_SOURCE_HASH_VLAN,
  OSC_NODE_AVB_SOURCE_HASH_STATE,
  OSC_NODE_AVB_SOURCES,
  OSC_NODE_AVB_SINKS,
  OSC_NODE_AVB_PTP,
  OSC_NODE_AVB_PTP_GM,
  OSC_NODE_AVB_PTP_PORTS,
  OSC_NODE_AVB_PTP_RATERATIO,
  OSC_NODE_AVB_PTP_PORT,
  OSC_NODE_AVB_PTP_PORT_HASH,
  OSC_NODE_AVB_PTP_PORT_HASH_PDELAY,
  OSC_NODE_AVB_SINK,
  OSC_NODE_AVB_SINK_HASH,
  OSC_NODE_AVB_SINK_HASH_CHANNELS,
  OSC_NODE_AVB_SINK_HASH_SYNC,
  OSC_NODE_AVB_SINK_HASH_NAME,
  OSC_NODE_AVB_SINK_HASH_VLAN,
  OSC_NODE_AVB_SINK_HASH_STATE,
  OSC_NODE_AVB_SINK_HASH_MAP,
  OSC_NODE_AVB_SINK_HASH_ID,
  OSC_NODE_AVB_SINK_HASH_ADDR,
  OSC_NODE_MEDIA,
  OSC_NODE_MEDIA_OUT,
  OSC_NODE_MEDIA_OUT_HASH,
  OSC_NODE_MEDIA_OUT_HASH_NAME,
  OSC_NODE_MEDIA_OUT_HASH_TYPE,
  OSC_NODE_MEDIA_OUTS,
  OSC_NODE_MEDIA_INS,
  OSC_NODE_MEDIA_IN,
  OSC_NODE_MEDIA_IN_HASH,
  OSC_NODE_MEDIA_IN_HASH_NAME,
  OSC_NODE_MEDIA_IN_HASH_TYPE,
  OSC_NODE_DEVICE,
  OSC_NODE_DEVICE_MEDIA_CLOCK,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_SOURCE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_RATE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_TYPE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_STATE,
  OSC_NODE_DEVICE_SYSTEM,
  OSC_NODE_DEVICE_IDENTITY,
  OSC_NODE_DEVICE_IDENTITY_SERIAL,
  OSC_NODE_DEVICE_IDENTITY_VERSION,
  OSC_NODE_DEVICE_IDENTITY_VENDOR_ID,
  OSC_NODE_DEVICE_IDENTITY_PRODUCT,
  OSC_NODE_DEVICE_IDENTITY_VENDOR,
  OSC_NODE_DEVICE_NAME,
  OSC_NODE_DEVICE_MONITOR,
  OSC_NODE_DEVICE_MONITOR_SOURCE,
  OSC_NODE_DEVICE_MEDIA_CLOCKS,
};



extern osc_node osc_node_osc;
extern osc_node osc_node_osc_version;
extern osc_node osc_node_osc_type;
extern osc_node osc_node_osc_type_reports;
extern osc_node osc_node_osc_type_accepts;
extern osc_node osc_node_avb;
extern osc_node osc_node_avb_source;
extern osc_node osc_node_avb_source_hash;
extern osc_node osc_node_avb_source_hash_presentation;
extern osc_node osc_node_avb_source_hash_map;
extern osc_node osc_node_avb_source_hash_dest;
extern osc_node osc_node_avb_source_hash_format;
extern osc_node osc_node_avb_source_hash_channels;
extern osc_node osc_node_avb_source_hash_sync;
extern osc_node osc_node_avb_source_hash_name;
extern osc_node osc_node_avb_source_hash_id;
extern osc_node osc_node_avb_source_hash_vlan;
extern osc_node osc_node_avb_source_hash_state;
extern osc_node osc_node_avb_sources;
extern osc_node osc_node_avb_sinks;
extern osc_node osc_node_avb_ptp;
extern osc_node osc_node_avb_ptp_gm;
extern osc_node osc_node_avb_ptp_ports;
extern osc_node osc_node_avb_ptp_rateratio;
extern osc_node osc_node_avb_ptp_port;
extern osc_node osc_node_avb_ptp_port_hash;
extern osc_node osc_node_avb_ptp_port_hash_pdelay;
extern osc_node osc_node_avb_sink;
extern osc_node osc_node_avb_sink_hash;
extern osc_node osc_node_avb_sink_hash_channels;
extern osc_node osc_node_avb_sink_hash_sync;
extern osc_node osc_node_avb_sink_hash_name;
extern osc_node osc_node_avb_sink_hash_vlan;
extern osc_node osc_node_avb_sink_hash_state;
extern osc_node osc_node_avb_sink_hash_map;
extern osc_node osc_node_avb_sink_hash_id;
extern osc_node osc_node_avb_sink_hash_addr;
extern osc_node osc_node_media;
extern osc_node osc_node_media_out;
extern osc_node osc_node_media_out_hash;
extern osc_node osc_node_media_out_hash_name;
extern osc_node osc_node_media_out_hash_type;
extern osc_node osc_node_media_outs;
extern osc_node osc_node_media_ins;
extern osc_node osc_node_media_in;
extern osc_node osc_node_media_in_hash;
extern osc_node osc_node_media_in_hash_name;
extern osc_node osc_node_media_in_hash_type;
extern osc_node osc_node_device;
extern osc_node osc_node_device_media_clock;
extern osc_node osc_node_device_media_clock_hash;
extern osc_node osc_node_device_media_clock_hash_source;
extern osc_node osc_node_device_media_clock_hash_rate;
extern osc_node osc_node_device_media_clock_hash_type;
extern osc_node osc_node_device_media_clock_hash_state;
extern osc_node osc_node_device_system;
extern osc_node osc_node_device_identity;
extern osc_node osc_node_device_identity_serial;
extern osc_node osc_node_device_identity_version;
extern osc_node osc_node_device_identity_vendor_id;
extern osc_node osc_node_device_identity_product;
extern osc_node osc_node_device_identity_vendor;
extern osc_node osc_node_device_name;
extern osc_node osc_node_device_monitor;
extern osc_node osc_node_device_monitor_source;
extern osc_node osc_node_device_media_clocks;


#endif // _osc_tree_h_
