// Autogenerated OSC data
#ifndef _osc_tree_h_
#define _osc_tree_h_
#include <xccompat.h>


#ifdef __XC__
#define REFERENCE_TO
#else
#define REFERENCE_TO &
#endif

enum osc_node_type {
  OSC_NODE_OSC,
  OSC_NODE_OSC_VERSION,
  OSC_NODE_OSC_TYPE,
  OSC_NODE_OSC_TYPE_REPORTS,
  OSC_NODE_OSC_TYPE_ACCEPTS,
  OSC_NODE_AVB,
  OSC_NODE_AVB_SOURCE,
  OSC_NODE_AVB_SOURCE_HASH,
  OSC_NODE_AVB_SOURCE_HASH_PRESENTATION,
  OSC_NODE_AVB_SOURCE_HASH_MAP,
  OSC_NODE_AVB_SOURCE_HASH_DEST,
  OSC_NODE_AVB_SOURCE_HASH_FORMAT,
  OSC_NODE_AVB_SOURCE_HASH_CHANNELS,
  OSC_NODE_AVB_SOURCE_HASH_SYNC,
  OSC_NODE_AVB_SOURCE_HASH_NAME,
  OSC_NODE_AVB_SOURCE_HASH_ID,
  OSC_NODE_AVB_SOURCE_HASH_VLAN,
  OSC_NODE_AVB_SOURCE_HASH_STATE,
  OSC_NODE_AVB_SOURCES,
  OSC_NODE_AVB_SINKS,
  OSC_NODE_AVB_PTP,
  OSC_NODE_AVB_PTP_GM,
  OSC_NODE_AVB_PTP_PORTS,
  OSC_NODE_AVB_PTP_RATERATIO,
  OSC_NODE_AVB_PTP_PORT,
  OSC_NODE_AVB_PTP_PORT_HASH,
  OSC_NODE_AVB_PTP_PORT_HASH_PDELAY,
  OSC_NODE_AVB_SINK,
  OSC_NODE_AVB_SINK_HASH,
  OSC_NODE_AVB_SINK_HASH_CHANNELS,
  OSC_NODE_AVB_SINK_HASH_SYNC,
  OSC_NODE_AVB_SINK_HASH_NAME,
  OSC_NODE_AVB_SINK_HASH_VLAN,
  OSC_NODE_AVB_SINK_HASH_STATE,
  OSC_NODE_AVB_SINK_HASH_MAP,
  OSC_NODE_AVB_SINK_HASH_ID,
  OSC_NODE_AVB_SINK_HASH_ADDR,
  OSC_NODE_MEDIA,
  OSC_NODE_MEDIA_OUT,
  OSC_NODE_MEDIA_OUT_HASH,
  OSC_NODE_MEDIA_OUT_HASH_NAME,
  OSC_NODE_MEDIA_OUT_HASH_TYPE,
  OSC_NODE_MEDIA_OUTS,
  OSC_NODE_MEDIA_INS,
  OSC_NODE_MEDIA_IN,
  OSC_NODE_MEDIA_IN_HASH,
  OSC_NODE_MEDIA_IN_HASH_NAME,
  OSC_NODE_MEDIA_IN_HASH_TYPE,
  OSC_NODE_DEVICE,
  OSC_NODE_DEVICE_MEDIA_CLOCK,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_SOURCE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_RATE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_TYPE,
  OSC_NODE_DEVICE_MEDIA_CLOCK_HASH_STATE,
  OSC_NODE_DEVICE_SYSTEM,
  OSC_NODE_DEVICE_IDENTITY,
  OSC_NODE_DEVICE_IDENTITY_SERIAL,
  OSC_NODE_DEVICE_IDENTITY_VERSION,
  OSC_NODE_DEVICE_IDENTITY_VENDOR_ID,
  OSC_NODE_DEVICE_IDENTITY_PRODUCT,
  OSC_NODE_DEVICE_IDENTITY_VENDOR,
  OSC_NODE_DEVICE_NAME,
  OSC_NODE_DEVICE_MONITOR,
  OSC_NODE_DEVICE_MONITOR_SOURCE,
  OSC_NODE_DEVICE_MEDIA_CLOCKS,
};



extern osc_node osc_node_osc;
extern osc_node osc_node_osc_version;
extern osc_node osc_node_osc_type;
extern osc_node osc_node_osc_type_reports;
extern osc_node osc_node_osc_type_accepts;
extern osc_node osc_node_avb;
extern osc_node osc_node_avb_source;
extern osc_node osc_node_avb_source_hash;
extern osc_node osc_node_avb_source_hash_presentation;
extern osc_node osc_node_avb_source_hash_map;
extern osc_node osc_node_avb_source_hash_dest;
extern osc_node osc_node_avb_source_hash_format;
extern osc_node osc_node_avb_source_hash_channels;
extern osc_node osc_node_avb_source_hash_sync;
extern osc_node osc_node_avb_source_hash_name;
extern osc_node osc_node_avb_source_hash_id;
extern osc_node osc_node_avb_source_hash_vlan;
extern osc_node osc_node_avb_source_hash_state;
extern osc_node osc_node_avb_sources;
extern osc_node osc_node_avb_sinks;
extern osc_node osc_node_avb_ptp;
extern osc_node osc_node_avb_ptp_gm;
extern osc_node osc_node_avb_ptp_ports;
extern osc_node osc_node_avb_ptp_rateratio;
extern osc_node osc_node_avb_ptp_port;
extern osc_node osc_node_avb_ptp_port_hash;
extern osc_node osc_node_avb_ptp_port_hash_pdelay;
extern osc_node osc_node_avb_sink;
extern osc_node osc_node_avb_sink_hash;
extern osc_node osc_node_avb_sink_hash_channels;
extern osc_node osc_node_avb_sink_hash_sync;
extern osc_node osc_node_avb_sink_hash_name;
extern osc_node osc_node_avb_sink_hash_vlan;
extern osc_node osc_node_avb_sink_hash_state;
extern osc_node osc_node_avb_sink_hash_map;
extern osc_node osc_node_avb_sink_hash_id;
extern osc_node osc_node_avb_sink_hash_addr;
extern osc_node osc_node_media;
extern osc_node osc_node_media_out;
extern osc_node osc_node_media_out_hash;
extern osc_node osc_node_media_out_hash_name;
extern osc_node osc_node_media_out_hash_type;
extern osc_node osc_node_media_outs;
extern osc_node osc_node_media_ins;
extern osc_node osc_node_media_in;
extern osc_node osc_node_media_in_hash;
extern osc_node osc_node_media_in_hash_name;
extern osc_node osc_node_media_in_hash_type;
extern osc_node osc_node_device;
extern osc_node osc_node_device_media_clock;
extern osc_node osc_node_device_media_clock_hash;
extern osc_node osc_node_device_media_clock_hash_source;
extern osc_node osc_node_device_media_clock_hash_rate;
extern osc_node osc_node_device_media_clock_hash_type;
extern osc_node osc_node_device_media_clock_hash_state;
extern osc_node osc_node_device_system;
extern osc_node osc_node_device_identity;
extern osc_node osc_node_device_identity_serial;
extern osc_node osc_node_device_identity_version;
extern osc_node osc_node_device_identity_vendor_id;
extern osc_node osc_node_device_identity_product;
extern osc_node osc_node_device_identity_vendor;
extern osc_node osc_node_device_name;
extern osc_node osc_node_device_monitor;
extern osc_node osc_node_device_monitor_source;
extern osc_node osc_node_device_media_clocks;


#ifndef __AVB_SOURCE_FORMAT_T__
enum avb_source_format_t 
{
AVB_SOURCE_FORMAT_MBLA_24BIT,
};
#endif
#ifndef __AVB_SOURCE_STATE_T__
enum avb_source_state_t 
{
AVB_SOURCE_STATE_DISABLED,
AVB_SOURCE_STATE_POTENTIAL,
AVB_SOURCE_STATE_ENABLED,
};
#endif
#ifndef __AVB_SINK_STATE_T__
enum avb_sink_state_t 
{
AVB_SINK_STATE_DISABLED,
AVB_SINK_STATE_POTENTIAL,
AVB_SINK_STATE_ENABLED,
};
#endif
#ifndef __DEVICE_MEDIA_CLOCK_TYPE_T__
enum device_media_clock_type_t 
{
DEVICE_MEDIA_CLOCK_TYPE_PTP,
DEVICE_MEDIA_CLOCK_TYPE_STREAM,
};
#endif
#ifndef __DEVICE_MEDIA_CLOCK_STATE_T__
enum device_media_clock_state_t 
{
DEVICE_MEDIA_CLOCK_STATE_DISABLED,
DEVICE_MEDIA_CLOCK_STATE_ENABLED,
};
#endif


#ifndef __OSC_IMPL

int get_osc_version(char a0[]);
int get_osc_type_reports(char a0[]);
int get_osc_type_accepts(char a0[]);
int getset_avb_source_presentation(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_source_presentation(int h0,int a0)
{return getset_avb_source_presentation(1, h0,REFERENCE_TO a0);}

inline int get_avb_source_presentation(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_source_presentation(0, h0,a0);}

int getset_avb_source_map(int set, int h0,int a0[], REFERENCE_PARAM(int, a0_len));

inline int set_avb_source_map(int h0,int a0[], int a0_len)
{return getset_avb_source_map(1, h0,a0, REFERENCE_TO a0_len);}

inline int get_avb_source_map(int h0,int a0[], REFERENCE_PARAM(int, a0_len))
 {return getset_avb_source_map(0, h0,a0, a0_len);}

int getset_avb_source_dest(int set, int h0,unsigned char a0[], REFERENCE_PARAM(int, a0_len));

inline int set_avb_source_dest(int h0,unsigned char a0[], int a0_len)
{return getset_avb_source_dest(1, h0,a0, REFERENCE_TO a0_len);}

inline int get_avb_source_dest(int h0,unsigned char a0[], REFERENCE_PARAM(int, a0_len))
 {return getset_avb_source_dest(0, h0,a0, a0_len);}

int getset_avb_source_format(int set, int h0,REFERENCE_PARAM(enum avb_source_format_t, a0),REFERENCE_PARAM(int, a1));

inline int set_avb_source_format(int h0,enum avb_source_format_t a0,int a1)
{return getset_avb_source_format(1, h0,REFERENCE_TO a0,REFERENCE_TO a1);}

inline int get_avb_source_format(int h0,REFERENCE_PARAM(enum avb_source_format_t, a0),REFERENCE_PARAM(int, a1))
 {return getset_avb_source_format(0, h0,a0,a1);}

int getset_avb_source_channels(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_source_channels(int h0,int a0)
{return getset_avb_source_channels(1, h0,REFERENCE_TO a0);}

inline int get_avb_source_channels(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_source_channels(0, h0,a0);}

int getset_avb_source_sync(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_source_sync(int h0,int a0)
{return getset_avb_source_sync(1, h0,REFERENCE_TO a0);}

inline int get_avb_source_sync(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_source_sync(0, h0,a0);}

int getset_avb_source_name(int set, int h0,char a0[]);

inline int set_avb_source_name(int h0,char a0[])
{return getset_avb_source_name(1, h0,a0);}

inline int get_avb_source_name(int h0,char a0[])
 {return getset_avb_source_name(0, h0,a0);}

int get_avb_source_id(int h0,unsigned int a0[2]);
int getset_avb_source_vlan(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_source_vlan(int h0,int a0)
{return getset_avb_source_vlan(1, h0,REFERENCE_TO a0);}

inline int get_avb_source_vlan(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_source_vlan(0, h0,a0);}

int getset_avb_source_state(int set, int h0,REFERENCE_PARAM(enum avb_source_state_t, a0));

inline int set_avb_source_state(int h0,enum avb_source_state_t a0)
{return getset_avb_source_state(1, h0,REFERENCE_TO a0);}

inline int get_avb_source_state(int h0,REFERENCE_PARAM(enum avb_source_state_t, a0))
 {return getset_avb_source_state(0, h0,a0);}

int get_avb_sources(REFERENCE_PARAM(int, a0));
int get_avb_sinks(REFERENCE_PARAM(int, a0));
int get_avb_ptp_gm(unsigned char a0[], REFERENCE_PARAM(int, a0_len));
int get_avb_ptp_ports(REFERENCE_PARAM(int, a0));
int get_avb_ptp_rateratio(REFERENCE_PARAM(int, a0));
int get_avb_ptp_port_pdelay(int h0,REFERENCE_PARAM(int, a0));
int getset_avb_sink_channels(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_sink_channels(int h0,int a0)
{return getset_avb_sink_channels(1, h0,REFERENCE_TO a0);}

inline int get_avb_sink_channels(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_sink_channels(0, h0,a0);}

int getset_avb_sink_sync(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_sink_sync(int h0,int a0)
{return getset_avb_sink_sync(1, h0,REFERENCE_TO a0);}

inline int get_avb_sink_sync(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_sink_sync(0, h0,a0);}

int getset_avb_sink_name(int set, int h0,char a0[]);

inline int set_avb_sink_name(int h0,char a0[])
{return getset_avb_sink_name(1, h0,a0);}

inline int get_avb_sink_name(int h0,char a0[])
 {return getset_avb_sink_name(0, h0,a0);}

int getset_avb_sink_vlan(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_avb_sink_vlan(int h0,int a0)
{return getset_avb_sink_vlan(1, h0,REFERENCE_TO a0);}

inline int get_avb_sink_vlan(int h0,REFERENCE_PARAM(int, a0))
 {return getset_avb_sink_vlan(0, h0,a0);}

int getset_avb_sink_state(int set, int h0,REFERENCE_PARAM(enum avb_sink_state_t, a0));

inline int set_avb_sink_state(int h0,enum avb_sink_state_t a0)
{return getset_avb_sink_state(1, h0,REFERENCE_TO a0);}

inline int get_avb_sink_state(int h0,REFERENCE_PARAM(enum avb_sink_state_t, a0))
 {return getset_avb_sink_state(0, h0,a0);}

int getset_avb_sink_map(int set, int h0,int a0[], REFERENCE_PARAM(int, a0_len));

inline int set_avb_sink_map(int h0,int a0[], int a0_len)
{return getset_avb_sink_map(1, h0,a0, REFERENCE_TO a0_len);}

inline int get_avb_sink_map(int h0,int a0[], REFERENCE_PARAM(int, a0_len))
 {return getset_avb_sink_map(0, h0,a0, a0_len);}

int get_avb_sink_id(int h0,unsigned int a0[2]);
int getset_avb_sink_addr(int set, int h0,unsigned char a0[], REFERENCE_PARAM(int, a0_len));

inline int set_avb_sink_addr(int h0,unsigned char a0[], int a0_len)
{return getset_avb_sink_addr(1, h0,a0, REFERENCE_TO a0_len);}

inline int get_avb_sink_addr(int h0,unsigned char a0[], REFERENCE_PARAM(int, a0_len))
 {return getset_avb_sink_addr(0, h0,a0, a0_len);}

int getset_media_out_name(int set, int h0,char a0[]);

inline int set_media_out_name(int h0,char a0[])
{return getset_media_out_name(1, h0,a0);}

inline int get_media_out_name(int h0,char a0[])
 {return getset_media_out_name(0, h0,a0);}

int get_media_out_type(int h0,char a0[]);
int get_media_outs(REFERENCE_PARAM(int, a0));
int get_media_ins(REFERENCE_PARAM(int, a0));
int getset_media_in_name(int set, int h0,char a0[]);

inline int set_media_in_name(int h0,char a0[])
{return getset_media_in_name(1, h0,a0);}

inline int get_media_in_name(int h0,char a0[])
 {return getset_media_in_name(0, h0,a0);}

int get_media_in_type(int h0,char a0[]);
int getset_device_media_clock_source(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_device_media_clock_source(int h0,int a0)
{return getset_device_media_clock_source(1, h0,REFERENCE_TO a0);}

inline int get_device_media_clock_source(int h0,REFERENCE_PARAM(int, a0))
 {return getset_device_media_clock_source(0, h0,a0);}

int getset_device_media_clock_rate(int set, int h0,REFERENCE_PARAM(int, a0));

inline int set_device_media_clock_rate(int h0,int a0)
{return getset_device_media_clock_rate(1, h0,REFERENCE_TO a0);}

inline int get_device_media_clock_rate(int h0,REFERENCE_PARAM(int, a0))
 {return getset_device_media_clock_rate(0, h0,a0);}

int getset_device_media_clock_type(int set, int h0,REFERENCE_PARAM(enum device_media_clock_type_t, a0));

inline int set_device_media_clock_type(int h0,enum device_media_clock_type_t a0)
{return getset_device_media_clock_type(1, h0,REFERENCE_TO a0);}

inline int get_device_media_clock_type(int h0,REFERENCE_PARAM(enum device_media_clock_type_t, a0))
 {return getset_device_media_clock_type(0, h0,a0);}

int getset_device_media_clock_state(int set, int h0,REFERENCE_PARAM(enum device_media_clock_state_t, a0));

inline int set_device_media_clock_state(int h0,enum device_media_clock_state_t a0)
{return getset_device_media_clock_state(1, h0,REFERENCE_TO a0);}

inline int get_device_media_clock_state(int h0,REFERENCE_PARAM(enum device_media_clock_state_t, a0))
 {return getset_device_media_clock_state(0, h0,a0);}

int get_device_system(char a0[]);
int get_device_identity_serial(char a0[]);
int get_device_identity_version(char a0[]);
int get_device_identity_vendor_id(char a0[]);
int get_device_identity_product(char a0[]);
int get_device_identity_vendor(char a0[]);
int get_device_name(char a0[]);
int getset_device_monitor_source(int set, REFERENCE_PARAM(int, a0));

inline int set_device_monitor_source(int a0)
{return getset_device_monitor_source(1, REFERENCE_TO a0);}

inline int get_device_monitor_source(REFERENCE_PARAM(int, a0))
 {return getset_device_monitor_source(0, a0);}

int get_device_media_clocks(REFERENCE_PARAM(int, a0));

#endif // __OSC_IMPL


#endif // _osc_tree_h_
