SPHINX_PROJECT_NAME=XMOS AVB Design Guide
VERSION=5.1.0
DOXYGEN_DIRS=../module_avb ../module_avb_media_clock ../module_gptp ../module_avb_1722  ../module_avb_audio  ../module_avb_1722_maap  ../module_avb_srp ../module_avb_1722_1 ../app_simple_avb_demo
SOURCE_INCLUDE_DIRS=../module_avb ../module_avb_media_clock ../module_gptp ../module_avb_1722  ../module_avb_audio  ../module_avb_1722_maap  ../module_avb_srp ../module_avb_1722_1 ../app_simple_avb_demo
XDOC_DIR ?= ../../xdoc
BREADCRUMB_PREFIX=<li><a href="../../index.html">Home</a></li>
XDEDOC_TITLE_PREFIX=AVB
include $(XDOC_DIR)/Makefile.inc
